import os
import re
from unicodedata import lookup
from ase import Atoms
from ase.units import Ry
from ase.parallel import parprint
from ase.calculators.siesta import Siesta
from ase.calculators.siesta.parameters import Species, PAOBasisBlock
from src.structure import Perovskite, get_reduced_formula
from src.cleanfiles import cleanFiles

def get_PAO_block(dir):
    """Function to extract the PAO.Basis block from a basis.out file generated by SIESTA.
    Args:
        dir: Directory containing the basis.out file
    Returns:
        block_basis: String containing the PAO.Basis block extracted from the basis.out file
    """
    # Open the generated .out file to extract the basis block
    with open(os.path.join(dir, "basis.out")) as f:
        out = f.read()
    # Extract the ChemicalSpeciesLabel and PAO.Basis block from the output file
    blocks = re.search(
        r"%block ChemicalSpeciesLabel.*?%endblock PAO.Basis",
        out, re.S).group(0)
    # Split the block into ChemicalSpeciesLabel and PAO.Basis block and return the PAO.Basis block
    block_species, block_basis = blocks.split("\n\n", 1)
    return block_basis

def modify_basis(block_in, symbols, orbitals, auto_radii=True):
    """Function to modify the basis block from a basis.fdf file generated by SIESTA.
    For now, the function adds a polarization orbital to the A-site (Ba) in a perovskite structure.
    Args:
        block_in: String containing the basis block to be modified
        symbols: List of elements that should be modified (e.g. ['Ba'])
        orbitals: List of orbitals to be added (e.g. ['3d'])
        auto_radii: Boolean indicating whether to set rcut and rmatch to 0.0 (default: True)
    Returns:
        block_out: String containing the modified basis block
    """

    # Extract species labels (A.1, B.2, C.3)
    species = re.findall(r"\b[A-Z][a-zA-Z]*\.\d+\b", block_in)
    #print(species)
    elements = [s.split('.')[0] for s in species]
    #print(elements)
    lookup = {v: i for i, v in enumerate(elements)}
    indices = [lookup[x] for x in symbols]
    #print(indices)
    targets = [elements[i] for i in indices]

    for j in range(len(targets)):
        print(f"Adding {orbitals[j]} polarization orbital to {targets[j]}")

    #parprint('Added d-polarization orbital to the following species:', ", ".join(targets))
    #print(indices, elements[indices[0]])

    # Split basis block into blocks for each species
    positions = [block_in.index(s) for s in species]
    positions.append(len(block_in))
    blocks = [
        block_in[positions[i]:positions[i+1]]
        for i in range(len(species))
    ]
    # Remove the last line from the last block (contains %endblock PAO.Basis)
    blocks[-1] = "\n".join(blocks[-1].split("\n")[:-1])


    def _add_polarization_orb(block_in, orbital):
        """Helper function to add a polarization orbital to the A-site (Ba) in the basis block.
        Args:
            block_in: String containing the basis block for the A-site (Ba)
            orbital: String specifying the orbital to be added (e.g. '3d')
        Returns:
            block_out: String containing the modified basis block for the A-site (Ba) with the added polarization orbital
        """
        lines = block_in.rstrip().splitlines()

        # last orbital shell
        #last_shell = lines[-3:]

        #nums = list(map(int, re.findall(r"\d+", last_shell[0])))
        #n, l, nz = nums[:3]

        n = int(orbital[0])
        l_dict = {'s': 0, 'p': 1, 'd': 2, 'f': 3}
        l = l_dict[orbital[1]]

        pol_shell = [
            f" n={n}   {l}   1                         # n, l, Nzeta",
            "   9.000",
            "   1.000",
        ]

        # update number of l-shells
        header = lines[0].split()
        header[1] = f'{int(header[1]) + 1}  '
        lines[0] =  "                  ".join(header[0:3]) + " " + " ".join(header[3:])

        # append polarization shell
        lines.extend(pol_shell)

        block_out = "\n".join(lines) + "\n"
        return block_out
    
    for j, i in enumerate(indices):
        blocks[i] = _add_polarization_orb(blocks[i], orbitals[j])
    
    # Make new basis by joining the blocks together
    new_basis = "".join(blocks)
    # Split the input block into lines to extract the first 2 lines and the last line
    lines = block_in.splitlines()
    # Add the first 2 lines of the original basis block back to the top and the last line back to the end
    block_out = lines[0] + "\n" + lines[1] + "\n" + new_basis + "\n" + lines[-1]

    if auto_radii:
        block_out = re.sub(r"\b\d+\.\d+\b", "0.0", block_out)

    return block_out

def generate_basis(atoms, xcf='PBEsol', basis='DZPp',
                   EnergyShift=0.01, SplitNorm=0.15,
                   MeshCutoff=1000, kgrid=(10, 10, 10),
                   pseudo='PBEsol', dir=''):
    """Function to generate a basis.fdf file for a given perovskite structure using SIESTA.
    Args:
        ase_atoms: ASE Atoms object representing the structure
        xcf: Exchange-correlation functional to use (default: 'PBEsol')
        basis: Basis set to use for the calculation (default: 'DZP').
               If basis ends with (lower-case) p, a polarization orbital will be added to the A-site (Ba)
        EnergyShift: Energy shift for the basis functions in Ry (default: 0.01)
        SplitNorm: Split norm for the basis functions (default: 0.15)
        MeshCutoff: Mesh cutoff for the basis functions in Ry (default: 1000)
        kgrid: k-point grid for the calculation (default: (10, 10, 10))
        pseudo: Pseudopotential to use (default: 'PBEsol')
        dir: Directory to save the input file (default: current working directory)
    Returns:
        None (the function saves the generated basis.fdf file in the specified directory)
    """
    # Define current working directory and extract information from the atoms object
    cwd = os.getcwd()
    formula = get_reduced_formula(atoms)
    symbols = re.findall(r'[A-Z][a-z]*', formula)

    # Save original ASE_SIESTA_COMMAND
    orig_command = os.environ.get("ASE_SIESTA_COMMAND")
    # Force serial execution just for this run
    os.environ["ASE_SIESTA_COMMAND"] = "siesta < PREFIX.fdf > PREFIX.out"

    if basis.endswith('p'):
        targets = [symbols[0]]
        basis = basis[:-1]
        add_p = True
    elif basis.endswith('d'):
        targets = [symbols[0], symbols[1]]
        basis = basis[:-1]
        add_p = True
    else:
        add_p = False

    # Calculation parameters in a dictionary
    calc_params = {
        'label': f'basis',
        'xc': xcf,
        'basis_set': basis,
        'mesh_cutoff': 100 * Ry,
        'energy_shift': EnergyShift * Ry,
        'kpts': (1, 1, 1),
        'directory': dir,
        'pseudo_path': os.path.join(cwd, 'pseudos', f'{xcf}')
    }
    # fdf arguments in a dictionary
    fdf_args = {
        #'PAO.BasisSize': basis,
        'PAO.SplitNorm': SplitNorm,
        #'SCF.MustConverge' : 'F',
        'SCFMustConverge': False,
        'MaxSCFIterations': 0,
        'WriteForces': 'F',
        'WriteCoorXmol': 'F'
        #'SCF.DM.Tolerance': 1e-6,
    }
    # Set up the Siesta calculator
    calc = Siesta(**calc_params, fdf_arguments=fdf_args)
    atoms.calc = calc
    # Perform a single-point calculation to generate the .out file containing the basis block
    atoms.get_potential_energy()

    # Restore original command
    if orig_command is not None:
        os.environ["ASE_SIESTA_COMMAND"] = orig_command

    # Extract the basis block from the generated .out file
    block = get_PAO_block(dir)

    # If the original basis string ended with 'p', add a polarization orbital to the A-site
    if add_p:
        targets = [symbols[0]]

        orbitals_dict = {
                'Ba': '5d',
                'Sr': '4d',
                'Ti': '4f',
        }
        orbitals = [orbitals_dict[targets[i]] for i in range(len(targets))]

        block = modify_basis(block, targets, orbitals)

    # Save block to a basis.fdf file in the specified directory
    with open(os.path.join(dir, "basis.fdf"), "w") as f:
        f.write(block)

    # Remove intermediate files generated by the calculation, keeping only the important ones
    cleanFiles(directory=dir, confirm=False)

    #calc.write_input(atoms, 'energies')
    